#!/usr/bin/env bash

set -e

formatted_date () {
    date --iso-8601=s --utc --date="$1" | sed 's/+00:00/Z/'
}

project="$1"
check_id="$2"

if [ -z "$project" ] || [ -z "$check_id" ]
then
    echo "Usage: query PROJECT CHECK_ID"
    echo "e.g. query boclips-prod keycloak-sTJcJSO5NkM"
    exit 1
fi

token="$(gcloud auth application-default print-access-token)"
start_time="$(formatted_date "1 minute ago")"
end_time="$(formatted_date "now")"
filter='metric.type="monitoring.googleapis.com/uptime_check/request_latency"+AND+'
filter+='metric.label.check_id="'$check_id'"'
group_by_fields='aggregation.groupByFields=metric.label.\"check_id\"'
per_series_aligner='aggregation.perSeriesAligner=ALIGN_MEAN'
alignment_period='aggregation.alignmentPeriod=60s'
cross_series_reducer='aggregation.crossSeriesReducer=REDUCE_MEAN'
query="interval.startTime=$start_time"
query+="&interval.endTime=$end_time"
query+="&filter=$filter"
query+="&$group_by_fields"
query+="&$per_series_aligner"
query+="&$alignment_period"
query+="&$cross_series_reducer"

curl \
    --header "Authorization: Bearer $token" \
    "https://monitoring.googleapis.com/v3/projects/$project/timeSeries?$query"
