#!/usr/bin/env bash

set -eu

page_id="$1"
metric_id="$2"
timestamp="$3"
value="$4"

if [ -z "$page_id" ] || [ -z "$metric_id" ] || [ -z "$timestamp" ] || [ -z "$value" ] || [ -z "$STATUSPAGE_API_KEY" ]
then
    echo "Usage: STATUSPAGE_API_KEY=some-api-key set PAGE_ID METRIC_ID TIMESTAMP VALUE"
    echo "e.g. STATUSPAGE_API_KEY=some-key set asdfasdf zxcvzxcv 1610551933 401.2"
    exit 1
fi

url="https://api.statuspage.io/v1/pages/$page_id/metrics/$metric_id/data"

payload="$(jq \
    --raw-output \
    --null-input \
    --argjson timestamp "$timestamp" \
    --argjson value "$value" \
    '{ data: { timestamp: $timestamp, value: $value } }')"

curl \
    --include \
    "$url" \
    --header "Authorization: OAuth $STATUSPAGE_API_KEY" \
    --header "Content-Type: application/json" \
    --request POST \
    --data "$payload"

echo
